### ISSUE TITLE
Discussion on improving dependency management file

### ISSUE THREAD

**Issue by fellipessanha** [manydeps/cxxbuild#1]
The syntax may not be really scalable as is. If we think about some more complex libs, with some options or optional modules ([the tokio dependency in rust](https://docs.rs/tokio/latest/tokio/#authoring-applications) comes to mind), it may start to become more and more complex and unstructured.

I think following the rust example and having the dependency be managed in toml, or maybe json, to match the javascript/typescript experience may be more future proof of handling the dependencies.

**Comment by igormcoelho** [comment]
Fully agree @fellipessanha , its a good idea to support toml syntax or even some json/xml.
Syntax in toml can be quite straightforward, something like:

[all]
fmt = { git = "https...", branch = "9.1.0" , links = ["fmt"]}
m = {links = ["m"]}

[test]
catch2 = { git ... }

[dev]
cmake = { pip = ["cmake"], deps = ["ninja"]}
ninja:windows = { ... }
ninja:linux = { ... }

is this easier to understand than current cxxdeps.txt format? I guess, a simple solution is to use something like this to generate cxxdeps.txt automatically :)

**Comment by igormcoelho** [comment]
The only drawback I see is that some people may confuse it with some popular cargo toml syntax for rust, but at least this is more structured than pure txt.
